---
- name: Add key
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"
    state: present
- name: Add official nginx repository
  apt_repository:
    repo: "deb https://nginx.org/packages/ubuntu/ bionic nginx"
    state: present
    update_cache: true

- name: Install nginx web server
  apt:
    name: nginx
    state: latest