---
 - name: Add official nginx repository
   apt_repository: repo='deb'
   https://nginx.org/packages/ubuntu/ bionic nginx
   
 - name: Install nginx web server
   apt:
     name: nginx
     state: latest
     update_cache: yes